
[functions.authorization-check]
enabled = true
verify_jwt = false
import_map = "./functions/authorization-check/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/authorization-check/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/authorization-check/*.html" ]
[functions.ai-calorie-estimation]
enabled = true
verify_jwt = false
import_map = "./functions/ai-calorie-estimation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-calorie-estimation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-calorie-estimation/*.html" ]
